#!/usr/bin/env python3
"""Generate a structured markdown file listing commits per file after a given ref.

Inverts the by-commit listing produced by commit-file-changes.py: for each unique
file path touched in the range, lists every commit that touched it with the
operation type (A/M/D/R), the commit subject, and the short hash. Files grouped
by top-level directory then sorted alphabetically.
"""

import subprocess
import sys
from collections import defaultdict
from pathlib import Path

OUTPUT = Path("analysis/commits-per-file-post-v0.24.2.md")
SINCE = "3a7856c"


def run(cmd: list[str]) -> str:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"FATAL: {cmd}\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def parse_log(raw: str) -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Return list of (hash, subject, [(op, path), ...]) tuples in chronological order."""
    commits: list[tuple[str, str, list[tuple[str, str]]]] = []
    cur_hash = ""
    cur_subject = ""
    cur_files: list[tuple[str, str]] = []
    for line in raw.splitlines():
        if line.startswith("COMMIT "):
            if cur_hash:
                commits.append((cur_hash, cur_subject, cur_files))
            _, h, *subject_parts = line.split(" ", 2)
            cur_hash = h
            cur_subject = subject_parts[0] if subject_parts else ""
            cur_files = []
        elif line.strip():
            parts = line.split("\t")
            op = parts[0]
            # For renames (R100\told\tnew), record the new path; note rename in op
            if op.startswith("R") and len(parts) == 3:
                cur_files.append(("R", parts[2]))
            elif len(parts) == 2:
                cur_files.append((op, parts[1]))
    if cur_hash:
        commits.append((cur_hash, cur_subject, cur_files))
    return commits


def top_level(path: str) -> str:
    parts = path.split("/", 1)
    return parts[0] if parts else "(root)"


def main():
    raw = run(
        [
            "git",
            "log",
            "--reverse",
            "--name-status",
            "--format=COMMIT %h %s",
            f"{SINCE}..HEAD",
        ]
    )
    commits = parse_log(raw)
    print(f"{len(commits)} commits since {SINCE}")

    # file_path -> list of (hash, subject, op)
    by_file: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for h, subj, files in commits:
        for op, path in files:
            by_file[path].append((h, subj, op))

    print(f"{len(by_file)} unique file paths touched")

    # Group by top-level dir
    by_top: dict[str, list[str]] = defaultdict(list)
    for path in by_file:
        by_top[top_level(path)].append(path)

    lines: list[str] = []
    lines.append(f"# Commits Per File (since `{SINCE}` — v0.24.2)")
    lines.append("")
    lines.append(
        f"**{len(commits)} commits, {len(by_file)} unique file paths**, "
        "generated by `scripts/commits-per-file.py`."
    )
    lines.append("")
    lines.append(
        "Operation codes: `A` added, `M` modified, `D` deleted, `R` renamed-to "
        "(only the new path is tracked for renames)."
    )
    lines.append("")

    for top in sorted(by_top.keys()):
        lines.append(f"## `{top}/`")
        lines.append("")
        for path in sorted(by_top[top]):
            touches = by_file[path]
            lines.append(f"### `{path}`")
            lines.append("")
            lines.append(f"*{len(touches)} touch(es)*")
            lines.append("")
            for h, subj, op in touches:
                lines.append(f"- `{op}` `{h}` — {subj}")
            lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
