#!/usr/bin/env python3
"""Generate a structured markdown file listing files changed per commit after a given ref."""

import subprocess
import sys
from pathlib import Path

OUTPUT = Path("analysis/commits-post-v0.24.2.md")
SINCE = "3a7856c"


def run(cmd: list[str]) -> str:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"FATAL: {cmd}\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def main():
    # 1) commit list (most recent first)
    hashes = run(["git", "log", "--format=%h", f"{SINCE}..HEAD"]).splitlines()
    print(f"{len(hashes)} commits since {SINCE}")

    lines: list[str] = []
    lines.append(f"# Files Changed Per Commit (since `{SINCE}` — v0.24.2)")
    lines.append("")
    lines.append(f"**{len(hashes)} commits**, generated by `scripts/commit-file-changes.py`")
    lines.append("")

    for h in hashes:
        subject = run(["git", "log", "--format=%s", "-1", h])
        stat = run(["git", "show", "--stat", "--format=", h])

        lines.append(f"## `{h}` — {subject}")
        lines.append("")

        if not stat:
            lines.append("*(no file changes)*")
        else:
            lines.append("```")
            lines.append(stat)
            lines.append("```")
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
