#!/usr/bin/env tsx
/**
 * extract-test-import-chains — POC per-test-file import + transitive-pi-context-reach registry
 *
 * For each test file under a target package, enumerate:
 * - Direct imports from @davidorex/pi-context/* subpaths
 * - Local-module imports + their direct pi-context imports (1-level transitive)
 * - Reach classification: direct | transitive | none
 *
 * Output is a substrate fact-set the Explore agent VALIDATES rather than re-derives.
 * Per DEC-0019 (scripts surface gaps + serve as test surface).
 *
 * Usage:
 *   tsx scripts/orchestrator/extract-test-import-chains.ts --target packages/pi-workflows --output /tmp/import-chains-pi-workflows.md
 *
 * Limitations (POC):
 * - Regex-based; does not do full AST. Misses dynamic require + type-only imports
 * - Transitive resolution stops at 1 level. Multi-hop chains require AST tooling
 * - Does not classify which pi-context functions cascade through resolveContextDir vs not — just records the import edge
 */
import fs from "node:fs";
import path from "node:path";

interface Args {
	target: string;
	outputPath: string;
}

function parseArgs(argv: string[]): Args {
	const out: Partial<Args> = {};
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === "--target" && argv[i + 1]) {
			out.target = argv[i + 1];
			i++;
		} else if (argv[i] === "--output" && argv[i + 1]) {
			out.outputPath = argv[i + 1];
			i++;
		}
	}
	if (!out.target || !out.outputPath) {
		console.error("Required: --target <package-dir> --output </tmp/...md>");
		process.exit(2);
	}
	return out as Args;
}

function listTsFiles(dir: string, suffix: string): string[] {
	const out: string[] = [];
	const walk = (d: string) => {
		for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
			const full = path.join(d, entry.name);
			if (entry.isDirectory()) {
				if (entry.name === "node_modules" || entry.name === "dist" || entry.name === "test-fixtures") continue;
				walk(full);
			} else if (entry.isFile() && entry.name.endsWith(suffix)) {
				out.push(full);
			}
		}
	};
	walk(dir);
	return out;
}

const PI_CONTEXT_RE = /from ["']@davidorex\/pi-context(?:\/[a-z-]+)?["']/g;
const LOCAL_RE = /from ["'](\.[^"']+)["']/g;

function extractImports(file: string): { piContext: string[]; local: string[] } {
	const content = fs.readFileSync(file, "utf-8");
	const piContext: string[] = [];
	const local: string[] = [];
	for (const m of content.matchAll(PI_CONTEXT_RE)) {
		piContext.push(m[0].replace(/from ["']|["']/g, ""));
	}
	for (const m of content.matchAll(LOCAL_RE)) {
		local.push(m[1]);
	}
	return { piContext, local };
}

function resolveLocal(fromFile: string, spec: string): string | null {
	const dir = path.dirname(fromFile);
	const candidate = path.resolve(dir, spec);
	const tries = [
		candidate,
		`${candidate}.ts`,
		`${candidate}.tsx`,
		`${candidate}.js`,
		path.join(candidate, "index.ts"),
		path.join(candidate, "index.js"),
		// .js → .ts substitution (common ESM pattern)
		candidate.endsWith(".js") ? candidate.replace(/\.js$/, ".ts") : null,
	].filter(Boolean) as string[];
	for (const t of tries) {
		if (fs.existsSync(t) && fs.statSync(t).isFile()) return t;
	}
	return null;
}

interface Reach {
	file: string;
	directPiContext: string[];
	transitiveViaLocals: Array<{ local: string; piContextImports: string[] }>;
}

function classify(reach: Reach): "direct" | "transitive" | "none" {
	if (reach.directPiContext.length > 0) return "direct";
	if (reach.transitiveViaLocals.some((t) => t.piContextImports.length > 0)) return "transitive";
	return "none";
}

function main(): void {
	const args = parseArgs(process.argv.slice(2));
	const srcDir = path.join(args.target, "src");
	if (!fs.existsSync(srcDir)) {
		console.error(`No src/ at ${args.target}`);
		process.exit(3);
	}

	const testFiles = listTsFiles(srcDir, ".test.ts");
	const reaches: Reach[] = [];

	for (const tf of testFiles) {
		const imports = extractImports(tf);
		const transitive: Reach["transitiveViaLocals"] = [];
		for (const localSpec of imports.local) {
			const resolved = resolveLocal(tf, localSpec);
			if (!resolved) continue;
			const localImports = extractImports(resolved);
			if (localImports.piContext.length > 0) {
				transitive.push({ local: path.relative(args.target, resolved), piContextImports: localImports.piContext });
			}
		}
		reaches.push({
			file: path.relative(args.target, tf),
			directPiContext: imports.piContext,
			transitiveViaLocals: transitive,
		});
	}

	const lines: string[] = [];
	lines.push(`# Per-test-file pi-context reach registry — ${args.target}`);
	lines.push("");
	lines.push(`Generated by scripts/orchestrator/extract-test-import-chains.ts (POC; regex-based; 1-level transitive).`);
	lines.push("");
	lines.push(`Total test files: ${testFiles.length}`);
	const counts = { direct: 0, transitive: 0, none: 0 };
	for (const r of reaches) counts[classify(r)]++;
	lines.push(`Reach classification: direct=${counts.direct}, transitive=${counts.transitive}, none=${counts.none}`);
	lines.push("");
	lines.push("## Per-file reach");
	lines.push("");
	lines.push("| Test file | Reach | Direct pi-context imports | Transitive via local imports |");
	lines.push("|-----------|-------|---------------------------|------------------------------|");
	for (const r of reaches) {
		const cls = classify(r);
		const direct = r.directPiContext.length > 0 ? r.directPiContext.join(", ") : "—";
		const transit =
			r.transitiveViaLocals.length === 0
				? "—"
				: r.transitiveViaLocals.map((t) => `${t.local} → ${t.piContextImports.join(", ")}`).join("; ");
		lines.push(`| ${r.file} | ${cls} | ${direct} | ${transit} |`);
	}

	fs.writeFileSync(args.outputPath, lines.join("\n"), "utf-8");
	console.log(`Wrote ${args.outputPath}`);
	console.log(
		`Test files: ${testFiles.length}; direct: ${counts.direct}; transitive: ${counts.transitive}; none: ${counts.none}`,
	);
}

main();
